### ISSUE TITLE
AttributeError: 'Nominatim' object has no attribute 'geocoder'

### ISSUE THREAD

**Issue by DzianisSledneu** [alpha-beta-soup/errorgeopy#4]
What I've seen when tried repeat test request. Similar problem was when I did reverse geocoding with my own lat-long data from Russia.
![1](https://user-images.githubusercontent.com/12112581/28011202-320d11d8-656a-11e7-975f-6545f4414af4.png)

**Comment by alpha-beta-soup** [comment]
Hi thanks for this. There were no tests covering the case of not passing in a configuration object or file when instantiating the `GeocoderPool`. I've fixed this in https://github.com/alpha-beta-soup/errorgeopy/pull/5 and I'll merge when the automated build passes.
